apiVersion: v1
kind: Service
metadata:
  name: feedback-service
spec:
  type: NodePort
  selector:
    app: feedback-app
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30036

#Let's check whether it's working or not !

#check2
#
#check3
#Check4
