name: CI/CD Feedback App

on: 
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

  steps:
  - name: Checkout Code
    uses: actions/checkout@v3

  - name: Log in to docker
    uses: actions/checkout@v3
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }} 

  - name: Build and Push to docker hub
    uses: docker/build-push-action@v5
    with:
      context: .
      push: true
      tags: ${{ secrets.DOCKER_USERNAME }}/feedback-app:latest
  
  - name: Set up kubeconfig
    run: |
      echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
      export KUBECONFIG=kubeconfig.yaml

  - name: Deploy to Kubernetes
    run: |
      kubectl apply -f k8s/
      kubectl rollout status deployment.feedback-app  
